// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lohqcitqctvyuoucyyxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvaHFjaXRxY3R2eXVvdWN5eXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODUxODUsImV4cCI6MjA2MTA2MTE4NX0.6JmclQ-7uoAf92UFR51d666jE3yeo5alr2n_YFZo-nQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);